# Logistic Regression Coding Challenge

## Imports

In [8]:
import numpy as np
import pandas as pd

from sklearn import preprocessing
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

## The Dataset

The dataset we will be using is the Iris dataset, which is commonly used in learning classification. The Iris dataset is a multivariate dataset where each class refers to a type of iris plant. This dataset is free and is publicly available at the UCI Machine Learning Repository.

<div>
    <img src=https://upload.wikimedia.org/wikipedia/commons/4/49/Iris_germanica_%28Purple_bearded_Iris%29%2C_Wakehurst_Place%2C_UK_-_Diliff.jpg width=300px>
</div>

This dataset contains a set of 150 records with five attributes - Sepal Length, Sepal Width, Petal Length, Petal Width, and Species. Species is the type of iris plant we will be classifying.

Lets import the data to see what we are dealing with.

In [9]:
df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/classification_sprint/iris.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [24]:
dataset = df.copy()
X = dataset.drop('species',axis =1)
y = dataset['species']
scaler = preprocessing.StandardScaler()
scaler.fit(X)
Xscaler.transform(X)

array([[-9.00681170e-01,  1.03205722e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00, -1.24957601e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.38535265e+00,  3.37848329e-01, -1.39813811e+00,
        -1.31297673e+00],
       [-1.50652052e+00,  1.06445364e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.02184904e+00,  1.26346019e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-5.37177559e-01,  1.95766909e+00, -1.17067529e+00,
        -1.05003079e+00],
       [-1.50652052e+00,  8.00654259e-01, -1.34127240e+00,
        -1.18150376e+00],
       [-1.02184904e+00,  8.00654259e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.74885626e+00, -3.56360566e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00,  1.06445364e-01, -1.28440670e+00,
        -1.44444970e+00],
       [-5.37177559e-01,  1.49486315e+00, -1.28440670e+00,
        -1.31297673e+00],
       [-1.26418478e+00,  8.00654259e-01, -1.22754100e+00,
      

In [16]:
X_train

sepal_length  sepal_width  petal_length  petal_width
4             5.0          3.6           1.4          0.2
32            5.2          4.1           1.5          0.1
142           5.8          2.7           5.1          1.9
85            6.0          3.4           4.5          1.6
86            6.7          3.1           4.7          1.5
16            5.4          3.9           1.3          0.4
10            5.4          3.7           1.5          0.2
81            5.5          2.4           3.7          1.0
133           6.3          2.8           5.1          1.5
137           6.4          3.1           5.5          1.8
75            6.6          3.0           4.4          1.4
109           7.2          3.6           6.1          2.5
96            5.7          2.9           4.2          1.3
105           7.6          3.0           6.6          2.1
66            5.6          3.0           4.5          1.5
0             5.1          3.5           1.4          0.2
122           7.7          2.8           6.7          2.0
67            5.8          2.7           4.1          1.0
28            5.2          3.4           1.4          0.2
40            5.0          3.5           1.3          0.3
44            5.1          3.8           1.9          0.4
60            5.0          2.0           3.5          1.0
123           6.3          2.7           4.9          1.8
24            4.8          3.4           1.9          0.2
25            5.0          3.0           1.6          0.2
23            5.1          3.3           1.7          0.5
94            5.6          2.7           4.2          1.3
39            5.1          3.4           1.5          0.2
95            5.7          3.0           4.2          1.2
117           7.7          3.8           6.7          2.2
..            ...          ...           ...          ...
91            6.1          3.0           4.6          1.4
41            4.5          2.3           1.3          0.3
58            6.6          2.9           4.6          1.3
90            5.5          2.6           4.4          1.2
48            5.3          3.7           1.5          0.2
88            5.6          3.0           4.1          1.3
107           7.3          2.9           6.3          1.8
124           6.7          3.3           5.7          2.1
21            5.1          3.7           1.5          0.4
57            4.9          2.4           3.3          1.0
144           6.7          3.3           5.7          2.5
129           7.2          3.0           5.8          1.6
37            4.9          3.1           1.5          0.1
140           6.7          3.1           5.6          2.4
1             4.9          3.0           1.4          0.2
52            6.9          3.1           4.9          1.5
130           7.4          2.8           6.1          1.9
103           6.3          2.9           5.6          1.8
99            5.7          2.8           4.1          1.3
116           6.5          3.0           5.5          1.8
87            6.3          2.3           4.4          1.3
74            6.4          2.9           4.3          1.3
121           5.6          2.8           4.9          2.0
149           5.9          3.0           5.1          1.8
20            5.4          3.4           1.7          0.2
71            6.1          2.8           4.0          1.3
106           4.9          2.5           4.5          1.7
14            5.8          4.0           1.2          0.2
92            5.8          2.6           4.0          1.2
102           7.1          3.0           5.9          2.1

[112 rows x 4 columns]

## Question 1 - Data pre-processing

Write a function to pre-processing the data so that we can run it through the classifier. The function should:
* Split the data into features and labels
* Standardise the features using sklearn's ```StandardScaler```
* Split the data into 75% training and 25% testing data.
* Use the `train_test_split` method from `sklearn` to do this.
* Set random_state to equal 42 for this internal method. 

_**Function Specifications:**_
* Should take a dataframe as input.
* Should return two `tuples` of the form `(X_train, y_train), (X_test, y_test)`.

In [5]:
def data_preprocess(df):
    
    dataset = df.copy()
    y = dataset['species']
    X = dataset.drop(['species'],axis = 1)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
    
    return (X_train, y_train), (X_test, y_test)

In [7]:
(X_train, y_train), (X_test, y_test) = data_preprocess(df)
print(X_train[:2])
print(y_train[:2])
print(X_test[:2])
print(y_test[:2])

    sepal_length  sepal_width  petal_length  petal_width
4            5.0          3.6           1.4          0.2
32           5.2          4.1           1.5          0.1
4     Iris-setosa
32    Iris-setosa
Name: species, dtype: object
    sepal_length  sepal_width  petal_length  petal_width
73           6.1          2.8           4.7          1.2
18           5.7          3.8           1.7          0.3
73    Iris-versicolor
18        Iris-setosa
Name: species, dtype: object


_**Expected Outputs:**_

```python
(X_train, y_train), (X_test, y_test) = data_preprocess(df)
print(X_train[:2])
print(y_train[:2])
print(X_test[:2])
print(y_test[:2])
```

> ```
[[-1.02184904  1.26346019 -1.3412724  -1.31297673]
 [-0.7795133   2.42047502 -1.2844067  -1.4444497 ]]
['Iris-setosa' 'Iris-setosa']
[[ 0.31099753 -0.58776353  0.53529583  0.00175297]
 [-0.17367395  1.72626612 -1.17067529 -1.18150376]]
['Iris-versicolor' 'Iris-setosa']
```

## Question 2 - Training the Model

Now that we have formatted our data, we can fit a model using sklearn's `LogisticRegression` class with its default parameters. Write a function that will take as input `(X_train, y_train)` that we created previously, and return a trained model.

_**Function Specifications:**_
* Should take two numpy `arrays` as input in the form `(X_train, y_train)`.
* The returned model should be fitted to the data.

In [ ]:
def train_model(X_train, y_train):
    # your code here
    return

In [ ]:
lm = train_model(X_train, y_train)
print(lm.intercept_[0])
print(lm.coef_)

In [ ]:
np.array_equal(np.round(lm.intercept_, 8), np.array([-1.51717564, -0.85832387, -2.36787217]))

_**Expected Outputs:**_

```python
lm = train_model(X_train, y_train)
print(lm.intercept_[0])
print(lm.coef_)
```
```
-1.51717564311
[[-0.71766856  1.32377179 -1.60277458 -1.41952784]
 [ 0.16218186 -1.28166738  0.51973042 -0.65811392]
 [ 0.08010274 -0.1281464   1.71205143  2.34828867]]
```

## Testing the model

### Question 3.1

Now that you have trained your model, lets see how well it does on the test set. Write a function which returns the accuracy of your trained model when tested with the test set.

_**Function Specifications:**_
* Should take the fitted model and two numpy `arrays` `X_test, y_test` as input.
* Should return a `float` of the accuracy of the model. This number should be between zero and one.

In [ ]:
def calculate_accuracy(lm, X_test, y_test):
    # your code here
    return

In [ ]:
print(calculate_accuracy(lm,X_test,y_test))

_**Expected Outputs:**_
    
```python
print(calculate_accuracy(lm,X_test,y_test))
```
>```
0.947368421053
```

### Question 3.2

A confusion matrix is a table that is often used to describe the performance of a classification model (or "classifier") on a set of test data for which the true values are known. Confusion matrices gives us more information on where our model is going wrong - looking specifically at the performance caused by Type I & II errors. Write a function which returns the confusion matrix of your test set.

_**Function Specifications:**_
* Should take the fitted model and two numpy `arrays` `X_test, y_test` as input.
* Should return a confusion matrix

_**Hint**_ You don't need to do this manually, sklearn has a confusion matrix function.

In [ ]:
def conf_matrix(lm, X_test, y_test):
    # your code here
    return

In [ ]:
print(conf_matrix(lm,X_test,y_test))

_**Expected Outputs:**_
    
```python
print(conf_matrix(lm,X_test,y_test))
```
>```
[[15  0  0]
 [ 0  9  2]
 [ 0  0 12]]
 ```

### Question 3.3

Write a function which calculates the _multi-class_ Accuracy, Precision, Recall and F1 scores. Recall from your trains that the precision, recall and f1 scores are calculated by

$$
{\rm Precision} = \frac{\rm TP}{TP+FP}
$$

$$
{\rm Recall} = \frac{\rm TP}{TP+FN}
$$

$$
{\rm F1} = 2 \times \frac{\rm Recall \times Precision}{\rm Recall + Precision}
$$

<div>
<img src=https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/confusion_matrix.png>
</div>

As per the image above, these scores can be calculated from the elements of either a single column (precision on "predicted true") or a single row row (recall on "actual true"). 

Let's generalize this notion to multiple columns. If $i$ represents a row index, and $j$ represents a column index of a confusion matrix $C$ then we can write the recall for the $i^{\rm th}$ row as 
$$
R_i = \frac{ C_{ii} }{ \sum_j C_{ij} },
$$
the precesion of the $j^{\rm th}$ column as
$$
P_j = \frac{ C_{jj} }{ \sum_i C_{ij} },
$$
and the F1 score as
$$
F_i = 2 \times \frac{P_i \times R_i}{P_i + R_i}.
$$

Using these, calculate the _average_ recall, precision, and F1 scores for our $3\times 3$ confusion matrix. As an example, the average recall is $R=\frac{1}{N}\sum_i^N R_i$, where $N$ is the number of rows.

_**Function Specifications:**_
* Should take the fitted model and two numpy `arrays` `X_test, y_test` as input.
* Should return a tuple in the form (`Accuracy`, `Precision`, `Recall`, `F1-Score`)

_**HINT:**_
The autograder tests the value of each of these metrics seperately. If you only know how to calculate one metric, then return a tuple with that metric, and zeros for the other metrics. For example, if you only know how to calculate accurcacy, then return a tuple with `(accuracy, 0, 0, 0)`. If you can only calculate the accuracy and recall, then return `(accuracy, 0, recall, 0)`.

In [ ]:
def scores(lm, X_test, y_test):
    # your code here
    return

In [ ]:
(accuracy, precision, recall, f1) = scores(lm, X_test, y_test)    

print('Accuracy: %f' % accuracy)
print('Precision: %f' % precision)
print('Recall: %f' % recall)
print('F1 score: %f' % f1)

_**Expected Outputs:**_
```python
(accuracy, precision, recall, f1) = scores(lm,X_test,y_test)
    
print('Accuracy: %f' % accuracy)
print('Precision: %f' % precision)
print('Recall: %f' % recall)
print('F1 score: %f' % f1)
```
> ```
Accuracy: 0.947368
Precision: 0.952381
Recall: 0.939394
F1 score: 0.941026
```